name: Parse Courses Workflow

on:
  workflow_dispatch

jobs:
  parse_courses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow-test branch
        uses: actions/checkout@v4
        with:
          ref: workflow-test

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run enrolment checker
        run: python scripts/check_enrolments.py
