name: Send Newsletter

on:
  schedule:
    - cron: '49 8 * * 6'
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up SSH for recipients repo
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.RECIPIENTS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone private recipients repo
        run: |
          git clone git@github.com:kctong529/sisukas-newsletter-recipients.git

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Generate newsletter content
        run: |
          python scripts/generate_newsletter.py

      - name: Move email list into expected location
        run: |
          cp sisukas-newsletter-recipients/email_list.txt email_list.txt

      - name: Send newsletter
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: |
          chmod +x scripts/send_newsletter.sh
          ./scripts/send_newsletter.sh
